import type { Metadata } from "next";
import "./globals.scss";
import AppProvider from "./provider";

export const metadata: Metadata = {
  title: "Oliver Matthews",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AppProvider> {children}</AppProvider>
      </body>
    </html>
  );
}
